
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image:
  file: .gitpod.Dockerfile
tasks:
  - name: install package and check zsh and zsh plugin
    init: >
      yarn install --frozen-lockfile && npx projen
      sudo chmod +x ./.gitpod/oh-my-zsh.sh && ./.gitpod/oh-my-zsh.sh
  - name: run docker
    command: sudo docker-up & 
  - name: zsh plugin
    command: sudo chmod +x ./.gitpod/oh-my-zsh.sh && ./.gitpod/oh-my-zsh.sh
  - name: start zsh
    command: zsh
vscode:
  extensions:
    - dbaeumer.vscode-eslint